openapi: 3.0.3
info:
  title: Polaris Extended Management Service
  version: 0.0.2
  description: |
    Extended API for Apache Polaris, including support for additional object types and management operations.
servers:
  - url: "{scheme}://{host}/api/management/v1"
    description: Polaris API Server
    variables:
      scheme:
        description: Protocol (http or https)
        default: https
      host:
        description: Host address
        default: localhost
security:
  - OAuth2: []

paths:
  /objects/create:
    post:
      operationId: createObject
      description: Create a new object in Polaris
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ObjectRequest"
      responses:
        201:
          description: Object created successfully
        400:
          description: Invalid request data

  /objects/drop:
    post:
      operationId: dropObject
      description: Drop an existing object in Polaris
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ObjectIdentifier"
      responses:
        200:
          description: Object dropped successfully
        404:
          description: Object not found

  /objects/alter:
    put:
      operationId: alterObject
      description: Alter an existing object in Polaris
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlterObjectRequest"
      responses:
        200:
          description: Object altered successfully
        400:
          description: Invalid request data

  /objects/comment:
    post:
      operationId: commentObject
      description: Add or modify comments for an object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentRequest"
      responses:
        200:
          description: Comment added successfully
        400:
          description: Invalid request data

  /objects/show:
    get:
      operationId: showObject
      description: Retrieve metadata for an object
      parameters:
        - name: objectName
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Object metadata retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ObjectMetadata"
        404:
          description: Object not found

  /database/add:
    post:
      operationId: addDatabase
      description: Add a database configuration to Polaris
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DatabaseConfig"
      responses:
        200:
          description: Database added successfully
        400:
          description: Invalid request data

  /sync:
    post:
      operationId: syncObjects
      description: Sync all objects to a requesting database system
      responses:
        200:
          description: Sync completed successfully
        500:
          description: Internal error

  /udo/add:
    post:
      operationId: addUDO
      description: Add a user-defined object (UDO)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UDORequest"
      responses:
        201:
          description: UDO created successfully
        400:
          description: Invalid request data

  /hub/show:
    get:
      operationId: showHub
      description: List predefined UDOs
      responses:
        200:
          description: List of predefined UDOs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UDOList"

components:
  schemas:
    ObjectRequest:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string

    ObjectIdentifier:
      type: object
      properties:
        name:
          type: string

    AlterObjectRequest:
      type: object
      properties:
        name:
          type: string
        modifications:
          type: object
          additionalProperties:
            type: string

    CommentRequest:
      type: object
      properties:
        objectName:
          type: string
        comment:
          type: string

    ObjectMetadata:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        details:
          type: object
          additionalProperties:
            type: string

    DatabaseConfig:
      type: object
      properties:
        name:
          type: string
        config:
          type: object
          additionalProperties:
            type: string

    UDORequest:
      type: object
      properties:
        name:
          type: string
        jsonDefinition:
          type: object
          additionalProperties:
            type: string

    UDOList:
      type: object
      properties:
        udos:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              definition:
                type: object
                additionalProperties:
                  type: string
